### ISSUE TITLE
IncompleteJSONError with yajl2 on python3

### ISSUE THREAD

**Issue by lavr** [isagalaev/ijson#37]
Hi!
I have strage IncompleteJSONError on OS X with ijson 2.2 from pypi and yajl2 2.1.0 from homebrew:

    $ python3 -V
    Python 3.4.3

    $ echo '{"a": 1}' | python3 -c "import ijson.backends.yajl2 as ijson; import sys; print(list(ijson.items(sys.stdin, '')))"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/jsonstream/.env/lib/python3.4/site-packages/ijson/common.py", line 138, in items
        current, event, value = next(prefixed_events)
      File "/private/tmp/jsonstream/.env/lib/python3.4/site-packages/ijson/common.py", line 65, in parse
        for event, value in basic_events:
      File "/private/tmp/jsonstream/.env/lib/python3.4/site-packages/ijson/backends/yajl2.py", line 96, in basic_parse
        raise exception(error.decode('utf-8'))
    ijson.common.IncompleteJSONError: lexical error: invalid char in json text.
                                          {                     (right here) ------^

Looking for any ideas how to fix this.

**Comment by imposeren** [comment]
seems like some problem with unicode/bytes. I have similar problem on python2:


```
# -*- coding: utf-8 -*-
import codecs
import ijson.backends.yajl2 as yajl_ijson
import ijson.backends.python as py_ijson

import sys
reload(sys)
sys.setdefaultencoding('utf-8')


target_file_path = "./test.json"

with open(target_file_path) as f:
    for item in py_ijson.items(f, 'item'):
        # fine
        print(item)
        break

with codecs.open(target_file_path, encoding='utf-8') as f:
    for item in py_ijson.items(f, 'item'):
        # fine
        print(item)
        break


with open(target_file_path) as f:
    for item in yajl_ijson.items(f, 'item'):
        # fine
        print(item)
        break

with codecs.open(target_file_path, encoding='utf-8') as f:
    for item in yajl_ijson.items(f, 'item'):
        # IncompleteJSONError
        print(item)
        break

```

result:
```
'i1'
'i1'
'i1'
Traceback (most recent call last):
  File "demo.py", line 33, in <module>
    for item in yajl_ijson.items(f, 'item'):
  File "/home/imposeren/.virtualenvs/multitest/local/lib/python2.7/site-packages/ijson/common.py", line 138, in items
    current, event, value = next(prefixed_events)
  File "/home/imposeren/.virtualenvs/multitest/local/lib/python2.7/site-packages/ijson/common.py", line 65, in parse
    for event, value in basic_events:
  File "/home/imposeren/.virtualenvs/multitest/local/lib/python2.7/site-packages/ijson/backends/yajl/common.py", line 31, in basic_parse
    yajl.yajl_parse(handle, buffer)
  File "/home/imposeren/.virtualenvs/multitest/local/lib/python2.7/site-packages/ijson/backends/yajl/ctypes/yajl2.py", line 87, in yajl_parse
    raise exception(error.decode('utf-8'))
ijson.common.IncompleteJSONError: lexical error: invalid char in json text.
                                      [                     (right here) ------^

```

**Comment by isagalaev** [comment]
The problem here is that yalj expects input to be a byte array and `sys.stdin` in Python 3 is a unicode object. Use `sys.stdin.buffer` to access raw binary data. And regular files should be opened as `open(filename, 'rb')`.

(Sorry for neglecting this ticket for so long.)
