### ISSUE TITLE
Python3 support for yajl2_cffi

### ISSUE THREAD

**Issue by danvk** [isagalaev/ijson#49]
With Python 3.5, I get the following error:

```
Traceback (most recent call last):
  File "./streaming_feature_count.py", line 8, in <module>
    print('# features: %s' % sum(1 for _ in features))
  File "./streaming_feature_count.py", line 8, in <genexpr>
    print('# features: %s' % sum(1 for _ in features))
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/ijson/common.py", line 138, in items
    current, event, value = next(prefixed_events)
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/ijson/common.py", line 65, in parse
    for event, value in basic_events:
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/ijson/backends/yajl2_cffi.py", line 218, in basic_parse
    yajl_parse(handle, buffer)
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/ijson/backends/yajl2_cffi.py", line 179, in yajl_parse
    result = yajl.yajl_parse(handle, buffer, len(buffer))
TypeError: initializer for ctype 'unsigned char *' must be a bytes or list or tuple, not str
./streaming_feature_count.py sf-blocks.json  0.15s user 0.04s system 66% cpu 0.297 total
```

My code works fine in Python 2.7, however.

Here's the full code:
```python
#!/usr/bin/env python
# import ijson
import ijson.backends.yajl2_cffi as ijson
import sys

with open(sys.argv[1]) as f:
    features = ijson.items(f, 'features.item')
    print('# features: %s' % sum(1 for _ in features))
```

**Comment by isagalaev** [comment]
The fix is, explicitly open the file in binary mode (which is what Python 2.x did by default): `open(sys.argv[1], 'rb')`.

JSON is in fact binary data, a utf-8 encoded stream, and this is what the underlining C library expects on input, not an already decoded Python string in whatever internal representation it happened to be. In Python backend we were able to coerce those two input types to unicode on the fly and work on the decoded stream but we can't do that with the C library.
