### ISSUE TITLE
Two test failures on Python 2

### ISSUE THREAD

**Issue by jayvdb** [isagalaev/ijson#78]
```console
======================================================================
[   49s] FAIL: test_numbers (__main__.PythonParse)
[   49s] ----------------------------------------------------------------------
[   49s] Traceback (most recent call last):
[   49s]   File "tests.py", line 153, in test_numbers
[   49s]     self.assertEqual(types, [int, Decimal, Decimal])
[   49s] AssertionError: Lists differ: [<type 'int'>, <type 'int'>, <... != [<type 'int'>, <class 'decimal...
[   49s] 
[   49s] First differing element 1:
[   49s] <type 'int'>
[   49s] <class 'decimal.Decimal'>
[   49s] 
[   49s] - [<type 'int'>, <type 'int'>, <type 'int'>]
[   49s] + [<type 'int'>, <class 'decimal.Decimal'>, <class 'decimal.Decimal'>]
[   49s] 
[   49s] ======================================================================
[   49s] FAIL: test_surrogate_pairs (__main__.PythonParse)
[   49s] ----------------------------------------------------------------------
[   49s] Traceback (most recent call last):
[   49s]   File "tests.py", line 148, in test_surrogate_pairs
[   49s]     self.assertEqual(parsed_string, '💩')
[   49s] AssertionError: u'\ud83d\udca9' != u'\U0001f4a9'
[   49s] - \ud83d\udca9
[   49s] + \U0001f4a9
[   49s] 
[   49s] 
[   49s] ----------------------------------------------------------------------
[   49s] Ran 19 tests in 0.012s
[   49s] 
[   49s] FAILED (failures=2)
```

**Comment by jayvdb** [comment]
Fixed in https://github.com/ICRAR/ijson/commit/846a1ccc99d1729582a3b0879556d287cc8de46a
